### ISSUE TITLE
Using a development version of plone.restapi-angular 

### ISSUE THREAD

**Issue by sunew** [plone/plone.restapi-angular#15]
Hi :) 
I'm trying to setup running the module on a git checkout, to be able to debug and perhaps to participate with a pull request:)

I have an app generated with angular-cli. I use the distribution of  plone.restapi-angular in my app, and this works fine. (Install via npm / package.json)

To run on the git checkout:

I use npm link and the method described here: 

https://github.com/angular/angular-cli/wiki/stories-linked-library

I add the peerdependencies to tsconfig.json, and build the aot version (build succeeds, apparently).

cd node_modules/@plone/restapi-angular
npm run build:aot

But I cannot make it work when serving my app:

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /work/projects/integrationsviden2-p5.1/resources/node_modules/@plone/restapi-angular/node_modules/@angular/core/core.d.ts, resolving symbol RESTAPIModule in /work/projects/integrationsviden2-p5.1/resources/node_modules/@plone/restapi-angular/dist/module.d.ts, resolving symbol RESTAPIModule in /work/projects/integrationsviden2-p5.1/resources/node_modules/@plone/restapi-angular/dist/module.d.ts
    at positionalError (/work/projects/integrationsviden2-p5.1/resources/node_modules/@angular/compiler/bundles/compiler.umd.js:25104:35)

My question is:
How do you run developing the library yourself? It would be great if you can share your setup.

Thanks, Sune

**Comment by ebrehault** [comment]
Last time I checked (few month ago), `npm link` and TypeScript were not playing nicely together.
So I do not have at the moment a convinient way to work with a library checkout into a dev project (my approach up to now is to work in the `./tests` folder into the restapi-angular package were I copy ./src into tests/src/app/lib, see https://github.com/plone/plone.restapi-angular/blob/master/package.json#L12, and, yes, I know, it sucks...)

But link/TypeScript might be fixed by now, we definitely need to check that.

**Comment by sunew** [comment]
okay:) I think i will try the same approach, integrating the lib src as a module into my app setup, and see if I can get my angular-cli setup to compile it. 
Thanks! I'll report if I have any luck :)

**Comment by sunew** [comment]
Okay, I created this workflow:

1. a script `develop-plone-restapi-angular.sh`, cloning and symlinking into the src

```
#!/bin/sh
# Run me from project root
mkdir develop
cd develop
git clone git@github.com:plone/plone.restapi-angular.git
cd ..
ln -s ../../develop/plone.restapi-angular/src/ ./src/app/plone-restapi-angular-lib
```

gitignore the develop folder and the symlink.

2. An imports wrapper, `plone-restapi-angular-imports.ts`, re-exporting the symbols my project use from the lib, defining a single point for changing between the git checkout and the distributed version in node_modules.

```
export {
  RESTAPIModule,
  PloneViews,
  Breadcrumbs,
  Navigation,
  GlobalNavigation,
  Services
} from '@plone/restapi-angular';
// } from './plone-restapi-angular-lib';

```

3. In all dependent modules, importing the symbols from the file from 2. :

`import { Breadcrumbs } from '../plone-restapi-angular-imports';
`

Now its super easy to clone and run on master:

run the script from project root.
revert the `from`-comment in the imports wrapper.

`debugger;`-breakpoints and sourcemaps in the lib works(see the attached image)

![selection_241](https://user-images.githubusercontent.com/893142/30553747-78426ba2-9ca2-11e7-90d7-b88b8d678982.png)

**Comment by ebrehault** [comment]
Seems good.
Just curious: did you try to symlink into ./node_modules? (so we don't need the import wrapper)

**Comment by sunew** [comment]
well, I think thats what npm link does. (looked like that when I tried)
Besides, our angular-cli build wont compile the files in node_modules (maybe its possible to make it do that ? )
