### ISSUE TITLE
Fix prod build

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi-angular#3]
`ng build --prod` is failing at the moment

**Comment by ebrehault** [comment]
Fixed with 1.0.0-alpha.15

**Comment by Glamurio** [comment]
Hey! So, while attempting to use `ng build --prod`, I get the following error message:

`ERROR in : Unexpected value 'TraversalModule in .../Documents/training/node_modules/angular-traversal/angular-traversal.d.ts' imported by the module 'RESTAPIModule in .../Documents/training/node_modules/@plone/restapi-angular/dist/module.d.ts'. Please add a @NgModule annotation.`

You mention this is something you fixed, but this is currently occuring on version 2.0.0, not sure if this is the same issue you ran into back then, but I'd appreciate the input!

**Comment by ebrehault** [comment]
For now, I recommend to get plone.restapi-angular using mrs-developer 9https://github.com/collective/mrs-developer), not using npm
