### ISSUE TITLE
Change suggestion: login() method returns an observable

### ISSUE THREAD

**Issue by tdesvenain** [plone/plone.restapi-angular#47]
All methods in `authenticated` and `api` services that make http requests returns observables, excepted `login` method.
`login` method contains a subscription to an http request that emits a new value for `isAuthenticated`.

This is quite good for implementing reactive behavior of components related to authenticated user.

This is not very convenient for implementing events that should happen just when the user has logged in.

I suggest that login() method returns an observable. The subscribe will be replaced : the update of isAuthenticated should be done in a do() operator.

This is a breaking change: the login() feature will be broken once the request won't be done.

Do you agree with this ? (if it is approved, I can make the change)

**Comment by tdesvenain** [comment]
@ebrehault @sunew @fulv @tisto

**Comment by fulv** [comment]
I agree this needs to happen.

**Comment by sunew** [comment]
I don't have an opinion right now :) I do not use the login yet, so no breaking things in my end.

**Comment by ebrehault** [comment]
Agreed
