### ISSUE TITLE
Local dev env not working

### ISSUE THREAD

**Issue by ajayns** [plone/plone.restapi-angular#51]
When I follow the steps for setup in README.md and install all packages and run ng serve, it's throwing this error
![image](https://user-images.githubusercontent.com/20743219/32646888-c80aa8c0-c614-11e7-8b09-ac8ed63d03bd.png)

@ebrehault @tdesvenain  Please help me out in this issue!

**Comment by ebrehault** [comment]
You should run it when you are in the `./tests` folder, not in the root.

Note: if you are looking for a good tutorial, try that one: https://training.plone.org/5/angular/index.html
