### ISSUE TITLE
Got an error building project from fresh npm install

### ISSUE THREAD

**Issue by mabhub** [plone/plone.restapi-angular#63]
`ERROR in Metadata version mismatch for module /msata/projets/ccha/node_modules/angular-traversal/dist/index.d.ts, found version 4, expected 3, resolving symbol RESTAPIModule in /msata/projets/ccha/node_modules/@plone/restapi-angular/dist/module.d.ts, resolving symbol RESTAPIModule in /msata/projets/ccha/node_modules/@plone/restapi-angular/dist/module.d.ts`

**Comment by ebrehault** [comment]
Which version of Angular are you using?

**Comment by mabhub** [comment]
```
> ng "version"

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.6
node: 9.3.0
os: linux x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/platform-server: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.0.6
@angular/compiler-cli: 4.4.6
```

_(All `4.4.6` versions are `^4.0.0` in `package.json` except ` @angular/platform-server ` which is `^4.2.3`)_

**Comment by ebrehault** [comment]
Then you should pin angular-traversal to 1.0.3.
Because the latest (1.0.4) is for Angular 5.

**Comment by mabhub** [comment]
It doesn't seems to work better : 
```
├─┬ @plone/restapi-angular@1.3.0
│ └── angular-traversal@1.0.3  deduped
└── angular-traversal@1.0.3 
```


`ERROR in /msata/projets/ccha/src/app/footer/footer.component.ts (19,11): Argument of type 'Traverser' is not assignable to parameter of type 'Services'.
  Property 'api' is missing in type 'Traverser'.`


`ERROR in Metadata version mismatch for module /msata/projets/ccha/node_modules/@plone/restapi-angular/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /msata/projets/ccha/src/app/app.module.ts, resolving symbol AppModule in /msata/projets/ccha/src/app/app.module.ts`
