### ISSUE TITLE
GlobalNavigation Links are empty

### ISSUE THREAD

**Issue by Glamurio** [plone/plone.restapi-angular#84]
Hello again! I'm running into a peculiar issue, when I was using the RestAPI on an older version, everything was working just fine, however after upgrading to a newer version, using the GlobalNavigation no longer works.

Previously it delivered all NavLinks neatly from the Plone, but now it returns an empty array. I suspect this is because you transitioned from global.navigation.js to global.navigation.ts and somewhere along the way it broke, but I might be wrong about that!

**Comment by Glamurio** [comment]
Okay, after tinkering with the problem I've found a way to solve it manually.
The issue occurs in `global.navigation.ts:32`

```
    component.refreshNavigation = component.services.navigation.refreshNavigation.pipe(
      mergeMap(() => component.services.resource.navigation())
    ).subscribe((links: NavLink[]) => {
      this.setLinks(links);
    });
```
The Observable at `resource.service.ts:231` never actually returns anything because the application seems to ignore it entirely. I don't know why this happens, as the code inside it works perfectly fine.

The way I've solved it now is by simply copying the code from `resource.service.ts:231` into a `global-navigation.component.ts` that inherits from GlobalNavigation much like you'd expect. I naturally also define the NavLink, NavigationItem and NavigationItems interfaces again.

This is a relatively unsavory solution, so I'd still appreciate if you could look at this yourself, see if you can reproduce it. I'd like to know if this is somehow a localised issue or if this happens with anyone using this SDK.

**Comment by ebrehault** [comment]
could you try replacing the `mergeMap` with `concatMap`?

**Comment by Glamurio** [comment]
Yup, and that made no discernible difference, it still doesn't work.

It's important to note that even when I tried accessing `resource.service.ts:231` by itself it works just fine, as in, if I run `this.services.resource.navigation().subscribe(res => console.log(res)` inside my own `global-navigation.component.ts` I get a response with all NavLinks, which I can then iterate with an `*ngFor`.

I believe the issue lies with `refreshNavigation: Subscription;` in `global.navigation.ts`. I think the way the code currently runs, you're essentially needlessly declaring an additional Subscription, but I'm also not as knowledgable in this area so it's absolutely possible I'm overlooking something.

**Comment by ebrehault** [comment]
I guess we are missing an initial `next()` on `refreshNavigation` somewhere.

The best solution is probably to fix navigation.service:

- make refreshNavigation a BehaviorSubject:
```
refreshNavigation: BehaviorSubject<boolean> = new BehaviorSubject(true);
```
- make a `next(true)` instead of `emit()` in the constructor

That way, any component subscribing to it will get the initial `true`, and it will not block the call.

Please, make a pull request when you have it working :)

**Comment by Glamurio** [comment]
Yup, that did the trick. I've never made a pull request, so I might need some assistance.

**Comment by ebrehault** [comment]
Ok so I guess that if you use plone.restapi-angular, you are involved in Plone is some way.
If you haven't signed the Plone contributor agreement yet, see here: https://plone.org/foundation/contributors-agreement

Once done, this is how you can make a pull request:

- create a new branch in your plone.restapi-angular local repository (let's assume you name it `fix-navigation`):

```
git checkout -b fix-navigation
```

- commit your fix:

```
git commit -am "Fix global navigation"
```

- push your branch:

```
git push origin fix-navigation
```

And then click on the provided link to create the pull request.

**Comment by Glamurio** [comment]
I'll have to read up on this contributor agreement and have to figure out how that aligns with our company stuff, but I'll make a pull request once I get that cleared up, in the meantime, I'll close the issue.

**Comment by ebrehault** [comment]
Oh ok, sure!
